ARG tag=1.14.0-py3
FROM tensorflow/tensorflow:${tag}
RUN apt-get update && \
    apt-get install -y --no-install-recommends libgl1 && \
    rm -rf /var/lib/apt/lists/*
RUN pip3 install --no-cache-dir --upgrade pip setuptools wheel 
RUN pip3 install --no-cache-dir tox pbr
ENV PBR_VERSION=1.0.0
CMD ["sleep", "infinity"]
